"""
Base de données complète des pays du monde (~190 pays).
"""


def get_flag(iso2: str) -> str:
    return "".join(chr(0x1F1E6 + ord(c) - ord("A")) for c in iso2.upper())


COUNTRIES = [
    # ══════════════════════════  FACILE  ══════════════════════════
    {
        "fr": "France",
        "en": "France",
        "capital_fr": "Paris",
        "iso2": "FR",
        "difficulty": "easy",
        "continent": "Europe",
    },
    {
        "fr": "Allemagne",
        "en": "Germany",
        "capital_fr": "Berlin",
        "iso2": "DE",
        "difficulty": "easy",
        "continent": "Europe",
    },
    {
        "fr": "Espagne",
        "en": "Spain",
        "capital_fr": "Madrid",
        "iso2": "ES",
        "difficulty": "easy",
        "continent": "Europe",
    },
    {
        "fr": "Italie",
        "en": "Italy",
        "capital_fr": "Rome",
        "iso2": "IT",
        "difficulty": "easy",
        "continent": "Europe",
    },
    {
        "fr": "Portugal",
        "en": "Portugal",
        "capital_fr": "Lisbonne",
        "iso2": "PT",
        "difficulty": "easy",
        "continent": "Europe",
    },
    {
        "fr": "Royaume-Uni",
        "en": "United Kingdom",
        "capital_fr": "Londres",
        "iso2": "GB",
        "difficulty": "easy",
        "continent": "Europe",
    },
    {
        "fr": "États-Unis",
        "en": "United States of America",
        "capital_fr": "Washington D.C.",
        "iso2": "US",
        "difficulty": "easy",
        "continent": "Amérique du Nord",
    },
    {
        "fr": "Canada",
        "en": "Canada",
        "capital_fr": "Ottawa",
        "iso2": "CA",
        "difficulty": "easy",
        "continent": "Amérique du Nord",
    },
    {
        "fr": "Mexique",
        "en": "Mexico",
        "capital_fr": "Mexico City",
        "iso2": "MX",
        "difficulty": "easy",
        "continent": "Amérique du Nord",
    },
    {
        "fr": "Brésil",
        "en": "Brazil",
        "capital_fr": "Brasília",
        "iso2": "BR",
        "difficulty": "easy",
        "continent": "Amérique du Sud",
    },
    {
        "fr": "Argentine",
        "en": "Argentina",
        "capital_fr": "Buenos Aires",
        "iso2": "AR",
        "difficulty": "easy",
        "continent": "Amérique du Sud",
    },
    {
        "fr": "Australie",
        "en": "Australia",
        "capital_fr": "Canberra",
        "iso2": "AU",
        "difficulty": "easy",
        "continent": "Océanie",
    },
    {
        "fr": "Japon",
        "en": "Japan",
        "capital_fr": "Tokyo",
        "iso2": "JP",
        "difficulty": "easy",
        "continent": "Asie",
    },
    {
        "fr": "Chine",
        "en": "China",
        "capital_fr": "Pékin",
        "iso2": "CN",
        "difficulty": "easy",
        "continent": "Asie",
    },
    {
        "fr": "Inde",
        "en": "India",
        "capital_fr": "New Delhi",
        "iso2": "IN",
        "difficulty": "easy",
        "continent": "Asie",
    },
    {
        "fr": "Russie",
        "en": "Russia",
        "capital_fr": "Moscou",
        "iso2": "RU",
        "difficulty": "easy",
        "continent": "Europe",
    },
    {
        "fr": "Afrique du Sud",
        "en": "South Africa",
        "capital_fr": "Pretoria",
        "extra_capitals_fr": ["Le Cap", "Bloemfontein"],
        "iso2": "ZA",
        "difficulty": "easy",
        "continent": "Afrique",
    },
    {
        "fr": "Égypte",
        "en": "Egypt",
        "capital_fr": "Le Caire",
        "iso2": "EG",
        "difficulty": "easy",
        "continent": "Afrique",
    },
    {
        "fr": "Maroc",
        "en": "Morocco",
        "capital_fr": "Rabat",
        "iso2": "MA",
        "difficulty": "easy",
        "continent": "Afrique",
    },
    {
        "fr": "Turquie",
        "en": "Turkey",
        "capital_fr": "Ankara",
        "iso2": "TR",
        "difficulty": "easy",
        "continent": "Europe",
    },
    {
        "fr": "Grèce",
        "en": "Greece",
        "capital_fr": "Athènes",
        "iso2": "GR",
        "difficulty": "easy",
        "continent": "Europe",
    },
    {
        "fr": "Suède",
        "en": "Sweden",
        "capital_fr": "Stockholm",
        "iso2": "SE",
        "difficulty": "easy",
        "continent": "Europe",
    },
    {
        "fr": "Norvège",
        "en": "Norway",
        "capital_fr": "Oslo",
        "iso2": "NO",
        "difficulty": "easy",
        "continent": "Europe",
    },
    {
        "fr": "Pays-Bas",
        "en": "Netherlands",
        "capital_fr": "Amsterdam",
        "iso2": "NL",
        "difficulty": "easy",
        "continent": "Europe",
    },
    {
        "fr": "Belgique",
        "en": "Belgium",
        "capital_fr": "Bruxelles",
        "iso2": "BE",
        "difficulty": "easy",
        "continent": "Europe",
    },
    {
        "fr": "Suisse",
        "en": "Switzerland",
        "capital_fr": "Berne",
        "iso2": "CH",
        "difficulty": "easy",
        "continent": "Europe",
    },
    {
        "fr": "Pologne",
        "en": "Poland",
        "capital_fr": "Varsovie",
        "iso2": "PL",
        "difficulty": "easy",
        "continent": "Europe",
    },
    {
        "fr": "Ukraine",
        "en": "Ukraine",
        "capital_fr": "Kyiv",
        "iso2": "UA",
        "difficulty": "easy",
        "continent": "Europe",
    },
    {
        "fr": "Arabie saoudite",
        "en": "Saudi Arabia",
        "capital_fr": "Riyad",
        "iso2": "SA",
        "difficulty": "easy",
        "continent": "Asie",
    },
    {
        "fr": "Corée du Sud",
        "en": "S. Korea",
        "capital_fr": "Séoul",
        "iso2": "KR",
        "difficulty": "easy",
        "continent": "Asie",
    },
    # ══════════════════════════  MOYEN  ══════════════════════════
    {
        "fr": "Irlande",
        "en": "Ireland",
        "capital_fr": "Dublin",
        "iso2": "IE",
        "difficulty": "medium",
        "continent": "Europe",
    },
    {
        "fr": "Finlande",
        "en": "Finland",
        "capital_fr": "Helsinki",
        "iso2": "FI",
        "difficulty": "medium",
        "continent": "Europe",
    },
    {
        "fr": "Autriche",
        "en": "Austria",
        "capital_fr": "Vienne",
        "iso2": "AT",
        "difficulty": "medium",
        "continent": "Europe",
    },
    {
        "fr": "République tchèque",
        "en": "Czechia",
        "capital_fr": "Prague",
        "iso2": "CZ",
        "difficulty": "medium",
        "continent": "Europe",
    },
    {
        "fr": "Hongrie",
        "en": "Hungary",
        "capital_fr": "Budapest",
        "iso2": "HU",
        "difficulty": "medium",
        "continent": "Europe",
    },
    {
        "fr": "Roumanie",
        "en": "Romania",
        "capital_fr": "Bucarest",
        "iso2": "RO",
        "difficulty": "medium",
        "continent": "Europe",
    },
    {
        "fr": "Danemark",
        "en": "Denmark",
        "capital_fr": "Copenhague",
        "iso2": "DK",
        "difficulty": "medium",
        "continent": "Europe",
    },
    {
        "fr": "Bulgarie",
        "en": "Bulgaria",
        "capital_fr": "Sofia",
        "iso2": "BG",
        "difficulty": "medium",
        "continent": "Europe",
    },
    {
        "fr": "Croatie",
        "en": "Croatia",
        "capital_fr": "Zagreb",
        "iso2": "HR",
        "difficulty": "medium",
        "continent": "Europe",
    },
    {
        "fr": "Serbie",
        "en": "Serbia",
        "capital_fr": "Belgrade",
        "iso2": "RS",
        "difficulty": "medium",
        "continent": "Europe",
    },
    {
        "fr": "Luxembourg",
        "en": "Luxembourg",
        "capital_fr": "Luxembourg",
        "iso2": "LU",
        "difficulty": "medium",
        "continent": "Europe",
    },
    {
        "fr": "Colombie",
        "en": "Colombia",
        "capital_fr": "Bogota",
        "iso2": "CO",
        "difficulty": "medium",
        "continent": "Amérique du Sud",
    },
    {
        "fr": "Pérou",
        "en": "Peru",
        "capital_fr": "Lima",
        "iso2": "PE",
        "difficulty": "medium",
        "continent": "Amérique du Sud",
    },
    {
        "fr": "Venezuela",
        "en": "Venezuela",
        "capital_fr": "Caracas",
        "iso2": "VE",
        "difficulty": "medium",
        "continent": "Amérique du Sud",
    },
    {
        "fr": "Chili",
        "en": "Chile",
        "capital_fr": "Santiago",
        "iso2": "CL",
        "difficulty": "medium",
        "continent": "Amérique du Sud",
    },
    {
        "fr": "Cuba",
        "en": "Cuba",
        "capital_fr": "La Havane",
        "iso2": "CU",
        "difficulty": "medium",
        "continent": "Amérique du Nord",
    },
    {
        "fr": "Costa Rica",
        "en": "Costa Rica",
        "capital_fr": "San José",
        "iso2": "CR",
        "difficulty": "medium",
        "continent": "Amérique du Nord",
    },
    {
        "fr": "Thaïlande",
        "en": "Thailand",
        "capital_fr": "Bangkok",
        "iso2": "TH",
        "difficulty": "medium",
        "continent": "Asie",
    },
    {
        "fr": "Vietnam",
        "en": "Vietnam",
        "capital_fr": "Hanoï",
        "iso2": "VN",
        "difficulty": "medium",
        "continent": "Asie",
    },
    {
        "fr": "Philippines",
        "en": "Philippines",
        "capital_fr": "Manille",
        "iso2": "PH",
        "difficulty": "medium",
        "continent": "Asie",
    },
    {
        "fr": "Indonésie",
        "en": "Indonesia",
        "capital_fr": "Nusantara",
        "iso2": "ID",
        "difficulty": "medium",
        "continent": "Asie",
    },
    {
        "fr": "Pakistan",
        "en": "Pakistan",
        "capital_fr": "Islamabad",
        "iso2": "PK",
        "difficulty": "medium",
        "continent": "Asie",
    },
    {
        "fr": "Iran",
        "en": "Iran",
        "capital_fr": "Téhéran",
        "iso2": "IR",
        "difficulty": "medium",
        "continent": "Asie",
    },
    {
        "fr": "Irak",
        "en": "Iraq",
        "capital_fr": "Bagdad",
        "iso2": "IQ",
        "difficulty": "medium",
        "continent": "Asie",
    },
    {
        "fr": "Émirats arabes unis",
        "en": "United Arab Emirates",
        "capital_fr": "Abou Dabi",
        "iso2": "AE",
        "difficulty": "medium",
        "continent": "Asie",
    },
    {
        "fr": "Singapour",
        "en": "Singapore",
        "capital_fr": "Singapour",
        "iso2": "SG",
        "difficulty": "medium",
        "continent": "Asie",
    },
    {
        "fr": "Afghanistan",
        "en": "Afghanistan",
        "capital_fr": "Kaboul",
        "iso2": "AF",
        "difficulty": "medium",
        "continent": "Asie",
    },
    {
        "fr": "Liban",
        "en": "Lebanon",
        "capital_fr": "Beyrouth",
        "iso2": "LB",
        "difficulty": "medium",
        "continent": "Asie",
    },
    {
        "fr": "Kazakhstan",
        "en": "Kazakhstan",
        "capital_fr": "Astana",
        "iso2": "KZ",
        "difficulty": "medium",
        "continent": "Asie",
    },
    {
        "fr": "Myanmar",
        "en": "Myanmar",
        "capital_fr": "Naypyidaw",
        "iso2": "MM",
        "difficulty": "medium",
        "continent": "Asie",
    },
    {
        "fr": "Algérie",
        "en": "Algeria",
        "capital_fr": "Alger",
        "iso2": "DZ",
        "difficulty": "medium",
        "continent": "Afrique",
    },
    {
        "fr": "Nigéria",
        "en": "Nigeria",
        "capital_fr": "Abuja",
        "iso2": "NG",
        "difficulty": "medium",
        "continent": "Afrique",
    },
    {
        "fr": "Éthiopie",
        "en": "Ethiopia",
        "capital_fr": "Addis-Abeba",
        "iso2": "ET",
        "difficulty": "medium",
        "continent": "Afrique",
    },
    {
        "fr": "Kenya",
        "en": "Kenya",
        "capital_fr": "Nairobi",
        "iso2": "KE",
        "difficulty": "medium",
        "continent": "Afrique",
    },
    {
        "fr": "Tanzanie",
        "en": "Tanzania",
        "capital_fr": "Dodoma",
        "iso2": "TZ",
        "difficulty": "medium",
        "continent": "Afrique",
    },
    {
        "fr": "Nouvelle-Zélande",
        "en": "New Zealand",
        "capital_fr": "Wellington",
        "iso2": "NZ",
        "difficulty": "medium",
        "continent": "Océanie",
    },
    # ══════════════════════════  DIFFICILE  ══════════════════════════
    # Europe
    {
        "fr": "Islande",
        "en": "Iceland",
        "capital_fr": "Reykjavik",
        "iso2": "IS",
        "difficulty": "hard",
        "continent": "Europe",
    },
    {
        "fr": "Slovaquie",
        "en": "Slovakia",
        "capital_fr": "Bratislava",
        "iso2": "SK",
        "difficulty": "hard",
        "continent": "Europe",
    },
    {
        "fr": "Slovénie",
        "en": "Slovenia",
        "capital_fr": "Ljubljana",
        "iso2": "SI",
        "difficulty": "hard",
        "continent": "Europe",
    },
    {
        "fr": "Albanie",
        "en": "Albania",
        "capital_fr": "Tirana",
        "iso2": "AL",
        "difficulty": "hard",
        "continent": "Europe",
    },
    {
        "fr": "Lituanie",
        "en": "Lithuania",
        "capital_fr": "Vilnius",
        "iso2": "LT",
        "difficulty": "hard",
        "continent": "Europe",
    },
    {
        "fr": "Lettonie",
        "en": "Latvia",
        "capital_fr": "Riga",
        "iso2": "LV",
        "difficulty": "hard",
        "continent": "Europe",
    },
    {
        "fr": "Estonie",
        "en": "Estonia",
        "capital_fr": "Tallinn",
        "iso2": "EE",
        "difficulty": "hard",
        "continent": "Europe",
    },
    {
        "fr": "Biélorussie",
        "en": "Belarus",
        "capital_fr": "Minsk",
        "iso2": "BY",
        "difficulty": "hard",
        "continent": "Europe",
    },
    {
        "fr": "Moldavie",
        "en": "Moldova",
        "capital_fr": "Chișinău",
        "iso2": "MD",
        "difficulty": "hard",
        "continent": "Europe",
    },
    {
        "fr": "Macédoine du Nord",
        "en": "Macedonia",
        "capital_fr": "Skopje",
        "iso2": "MK",
        "difficulty": "hard",
        "continent": "Europe",
    },
    {
        "fr": "Bosnie-Herzégovine",
        "en": "Bosnia and Herz.",
        "capital_fr": "Sarajevo",
        "iso2": "BA",
        "difficulty": "hard",
        "continent": "Europe",
    },
    {
        "fr": "Monténégro",
        "en": "Montenegro",
        "capital_fr": "Podgorica",
        "iso2": "ME",
        "difficulty": "hard",
        "continent": "Europe",
    },
    {
        "fr": "Kosovo",
        "en": "Kosovo",
        "capital_fr": "Pristina",
        "iso2": "XK",
        "difficulty": "hard",
        "continent": "Europe",
    },
    {
        "fr": "Malte",
        "en": "Malta",
        "capital_fr": "La Valette",
        "iso2": "MT",
        "difficulty": "hard",
        "continent": "Europe",
    },
    {
        "fr": "Chypre",
        "en": "Cyprus",
        "capital_fr": "Nicosie",
        "iso2": "CY",
        "difficulty": "hard",
        "continent": "Europe",
    },
    {
        "fr": "Andorre",
        "en": "Andorra",
        "capital_fr": "Andorre-la-Vieille",
        "iso2": "AD",
        "difficulty": "hard",
        "continent": "Europe",
    },
    {
        "fr": "Liechtenstein",
        "en": "Liechtenstein",
        "capital_fr": "Vaduz",
        "iso2": "LI",
        "difficulty": "hard",
        "continent": "Europe",
    },
    {
        "fr": "Monaco",
        "en": "Monaco",
        "capital_fr": "Monaco",
        "iso2": "MC",
        "difficulty": "hard",
        "continent": "Europe",
    },
    # Asie
    {
        "fr": "Géorgie",
        "en": "Georgia",
        "capital_fr": "Tbilissi",
        "iso2": "GE",
        "difficulty": "hard",
        "continent": "Asie",
    },
    {
        "fr": "Arménie",
        "en": "Armenia",
        "capital_fr": "Erevan",
        "iso2": "AM",
        "difficulty": "hard",
        "continent": "Asie",
    },
    {
        "fr": "Azerbaïdjan",
        "en": "Azerbaijan",
        "capital_fr": "Bakou",
        "iso2": "AZ",
        "difficulty": "hard",
        "continent": "Asie",
    },
    {
        "fr": "Ouzbékistan",
        "en": "Uzbekistan",
        "capital_fr": "Tachkent",
        "iso2": "UZ",
        "difficulty": "hard",
        "continent": "Asie",
    },
    {
        "fr": "Mongolie",
        "en": "Mongolia",
        "capital_fr": "Oulan-Bator",
        "iso2": "MN",
        "difficulty": "hard",
        "continent": "Asie",
    },
    {
        "fr": "Bangladesh",
        "en": "Bangladesh",
        "capital_fr": "Dacca",
        "iso2": "BD",
        "difficulty": "hard",
        "continent": "Asie",
    },
    {
        "fr": "Népal",
        "en": "Nepal",
        "capital_fr": "Katmandou",
        "iso2": "NP",
        "difficulty": "hard",
        "continent": "Asie",
    },
    {
        "fr": "Syrie",
        "en": "Syria",
        "capital_fr": "Damas",
        "iso2": "SY",
        "difficulty": "hard",
        "continent": "Asie",
    },
    {
        "fr": "Jordanie",
        "en": "Jordan",
        "capital_fr": "Amman",
        "iso2": "JO",
        "difficulty": "hard",
        "continent": "Asie",
    },
    {
        "fr": "Oman",
        "en": "Oman",
        "capital_fr": "Mascate",
        "iso2": "OM",
        "difficulty": "hard",
        "continent": "Asie",
    },
    {
        "fr": "Malaisie",
        "en": "Malaysia",
        "capital_fr": "Kuala Lumpur",
        "iso2": "MY",
        "difficulty": "hard",
        "continent": "Asie",
    },
    {
        "fr": "Corée du Nord",
        "en": "N. Korea",
        "capital_fr": "Pyongyang",
        "iso2": "KP",
        "difficulty": "hard",
        "continent": "Asie",
    },
    {
        "fr": "Qatar",
        "en": "Qatar",
        "capital_fr": "Doha",
        "iso2": "QA",
        "difficulty": "hard",
        "continent": "Asie",
    },
    {
        "fr": "Koweït",
        "en": "Kuwait",
        "capital_fr": "Koweït City",
        "iso2": "KW",
        "difficulty": "hard",
        "continent": "Asie",
    },
    {
        "fr": "Bahreïn",
        "en": "Bahrain",
        "capital_fr": "Manama",
        "iso2": "BH",
        "difficulty": "hard",
        "continent": "Asie",
    },
    {
        "fr": "Yémen",
        "en": "Yemen",
        "capital_fr": "Sanaa",
        "iso2": "YE",
        "difficulty": "hard",
        "continent": "Asie",
    },
    {
        "fr": "Israël",
        "en": "Israel",
        "capital_fr": "Jérusalem",
        "iso2": "IL",
        "difficulty": "hard",
        "continent": "Asie",
    },
    {
        "fr": "Sri Lanka",
        "en": "Sri Lanka",
        "capital_fr": "Sri Jayawardenepura Kotte",
        "iso2": "LK",
        "difficulty": "hard",
        "continent": "Asie",
    },
    {
        "fr": "Cambodge",
        "en": "Cambodia",
        "capital_fr": "Phnom Penh",
        "iso2": "KH",
        "difficulty": "hard",
        "continent": "Asie",
    },
    {
        "fr": "Laos",
        "en": "Laos",
        "capital_fr": "Vientiane",
        "iso2": "LA",
        "difficulty": "hard",
        "continent": "Asie",
    },
    {
        "fr": "Kirghizistan",
        "en": "Kyrgyzstan",
        "capital_fr": "Bichkek",
        "iso2": "KG",
        "difficulty": "hard",
        "continent": "Asie",
    },
    {
        "fr": "Tadjikistan",
        "en": "Tajikistan",
        "capital_fr": "Douchanbé",
        "iso2": "TJ",
        "difficulty": "hard",
        "continent": "Asie",
    },
    {
        "fr": "Turkménistan",
        "en": "Turkmenistan",
        "capital_fr": "Achgabat",
        "iso2": "TM",
        "difficulty": "hard",
        "continent": "Asie",
    },
    {
        "fr": "Bhoutan",
        "en": "Bhutan",
        "capital_fr": "Thimphou",
        "iso2": "BT",
        "difficulty": "hard",
        "continent": "Asie",
    },
    {
        "fr": "Brunéi",
        "en": "Brunei",
        "capital_fr": "Bandar Seri Begawan",
        "iso2": "BN",
        "difficulty": "hard",
        "continent": "Asie",
    },
    {
        "fr": "Timor oriental",
        "en": "Timor-Leste",
        "capital_fr": "Dili",
        "iso2": "TL",
        "difficulty": "hard",
        "continent": "Asie",
    },
    # Afrique
    {
        "fr": "Angola",
        "en": "Angola",
        "capital_fr": "Luanda",
        "iso2": "AO",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Mozambique",
        "en": "Mozambique",
        "capital_fr": "Maputo",
        "iso2": "MZ",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Ghana",
        "en": "Ghana",
        "capital_fr": "Accra",
        "iso2": "GH",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Sénégal",
        "en": "Senegal",
        "capital_fr": "Dakar",
        "iso2": "SN",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Cameroun",
        "en": "Cameroon",
        "capital_fr": "Yaoundé",
        "iso2": "CM",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Tunisie",
        "en": "Tunisia",
        "capital_fr": "Tunis",
        "iso2": "TN",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Libye",
        "en": "Libya",
        "capital_fr": "Tripoli",
        "iso2": "LY",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Soudan",
        "en": "Sudan",
        "capital_fr": "Khartoum",
        "iso2": "SD",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Zimbabwe",
        "en": "Zimbabwe",
        "capital_fr": "Harare",
        "iso2": "ZW",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Zambie",
        "en": "Zambia",
        "capital_fr": "Lusaka",
        "iso2": "ZM",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Côte d'Ivoire",
        "en": "Ivory Coast",
        "capital_fr": "Yamoussoukro",
        "iso2": "CI",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Mali",
        "en": "Mali",
        "capital_fr": "Bamako",
        "iso2": "ML",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Niger",
        "en": "Niger",
        "capital_fr": "Niamey",
        "iso2": "NE",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Tchad",
        "en": "Chad",
        "capital_fr": "N'Djamena",
        "iso2": "TD",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Burkina Faso",
        "en": "Burkina Faso",
        "capital_fr": "Ouagadougou",
        "iso2": "BF",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Guinée",
        "en": "Guinea",
        "capital_fr": "Conakry",
        "iso2": "GN",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Sierra Leone",
        "en": "Sierra Leone",
        "capital_fr": "Freetown",
        "iso2": "SL",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Libéria",
        "en": "Liberia",
        "capital_fr": "Monrovia",
        "iso2": "LR",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Gambie",
        "en": "Gambia",
        "capital_fr": "Banjul",
        "iso2": "GM",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Guinée-Bissau",
        "en": "Guinea-Bissau",
        "capital_fr": "Bissau",
        "iso2": "GW",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Mauritanie",
        "en": "Mauritania",
        "capital_fr": "Nouakchott",
        "iso2": "MR",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Somalie",
        "en": "Somalia",
        "capital_fr": "Mogadiscio",
        "iso2": "SO",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Érythrée",
        "en": "Eritrea",
        "capital_fr": "Asmara",
        "iso2": "ER",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Djibouti",
        "en": "Djibouti",
        "capital_fr": "Djibouti",
        "iso2": "DJ",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Rwanda",
        "en": "Rwanda",
        "capital_fr": "Kigali",
        "iso2": "RW",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Burundi",
        "en": "Burundi",
        "capital_fr": "Gitega",
        "iso2": "BI",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Ouganda",
        "en": "Uganda",
        "capital_fr": "Kampala",
        "iso2": "UG",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Malawi",
        "en": "Malawi",
        "capital_fr": "Lilongwe",
        "iso2": "MW",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Namibie",
        "en": "Namibia",
        "capital_fr": "Windhoek",
        "iso2": "NA",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Botswana",
        "en": "Botswana",
        "capital_fr": "Gaborone",
        "iso2": "BW",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Lesotho",
        "en": "Lesotho",
        "capital_fr": "Maseru",
        "iso2": "LS",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Eswatini",
        "en": "eSwatini",
        "capital_fr": "Mbabane",
        "iso2": "SZ",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Madagascar",
        "en": "Madagascar",
        "capital_fr": "Antananarivo",
        "iso2": "MG",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Rép. centrafricaine",
        "en": "Central African Rep.",
        "capital_fr": "Bangui",
        "iso2": "CF",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Gabon",
        "en": "Gabon",
        "capital_fr": "Libreville",
        "iso2": "GA",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Guinée équatoriale",
        "en": "Eq. Guinea",
        "capital_fr": "Malabo",
        "iso2": "GQ",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Congo",
        "en": "Congo",
        "capital_fr": "Brazzaville",
        "iso2": "CG",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "RD Congo",
        "en": "Dem. Rep. Congo",
        "capital_fr": "Kinshasa",
        "iso2": "CD",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Soudan du Sud",
        "en": "S. Sudan",
        "capital_fr": "Djouba",
        "iso2": "SS",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Bénin",
        "en": "Benin",
        "capital_fr": "Porto-Novo",
        "iso2": "BJ",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    {
        "fr": "Togo",
        "en": "Togo",
        "capital_fr": "Lomé",
        "iso2": "TG",
        "difficulty": "hard",
        "continent": "Afrique",
    },
    # Amériques
    {
        "fr": "Équateur",
        "en": "Ecuador",
        "capital_fr": "Quito",
        "iso2": "EC",
        "difficulty": "hard",
        "continent": "Amérique du Sud",
    },
    {
        "fr": "Bolivie",
        "en": "Bolivia",
        "capital_fr": "Sucre",
        "extra_capitals_fr": ["La Paz"],
        "iso2": "BO",
        "difficulty": "hard",
        "continent": "Amérique du Sud",
    },
    {
        "fr": "Paraguay",
        "en": "Paraguay",
        "capital_fr": "Asunción",
        "iso2": "PY",
        "difficulty": "hard",
        "continent": "Amérique du Sud",
    },
    {
        "fr": "Uruguay",
        "en": "Uruguay",
        "capital_fr": "Montevideo",
        "iso2": "UY",
        "difficulty": "hard",
        "continent": "Amérique du Sud",
    },
    {
        "fr": "Guyana",
        "en": "Guyana",
        "capital_fr": "Georgetown",
        "iso2": "GY",
        "difficulty": "hard",
        "continent": "Amérique du Sud",
    },
    {
        "fr": "Suriname",
        "en": "Suriname",
        "capital_fr": "Paramaribo",
        "iso2": "SR",
        "difficulty": "hard",
        "continent": "Amérique du Sud",
    },
    {
        "fr": "Guatemala",
        "en": "Guatemala",
        "capital_fr": "Guatemala City",
        "iso2": "GT",
        "difficulty": "hard",
        "continent": "Amérique du Nord",
    },
    {
        "fr": "Panama",
        "en": "Panama",
        "capital_fr": "Panama City",
        "iso2": "PA",
        "difficulty": "hard",
        "continent": "Amérique du Nord",
    },
    {
        "fr": "Haïti",
        "en": "Haiti",
        "capital_fr": "Port-au-Prince",
        "iso2": "HT",
        "difficulty": "hard",
        "continent": "Amérique du Nord",
    },
    {
        "fr": "République dominicaine",
        "en": "Dominican Rep.",
        "capital_fr": "Saint-Domingue",
        "iso2": "DO",
        "difficulty": "hard",
        "continent": "Amérique du Nord",
    },
    {
        "fr": "Jamaïque",
        "en": "Jamaica",
        "capital_fr": "Kingston",
        "iso2": "JM",
        "difficulty": "hard",
        "continent": "Amérique du Nord",
    },
    {
        "fr": "Trinité-et-Tobago",
        "en": "Trinidad and Tobago",
        "capital_fr": "Port of Spain",
        "iso2": "TT",
        "difficulty": "hard",
        "continent": "Amérique du Nord",
    },
    {
        "fr": "Belize",
        "en": "Belize",
        "capital_fr": "Belmopan",
        "iso2": "BZ",
        "difficulty": "hard",
        "continent": "Amérique du Nord",
    },
    {
        "fr": "El Salvador",
        "en": "El Salvador",
        "capital_fr": "San Salvador",
        "iso2": "SV",
        "difficulty": "hard",
        "continent": "Amérique du Nord",
    },
    {
        "fr": "Honduras",
        "en": "Honduras",
        "capital_fr": "Tegucigalpa",
        "iso2": "HN",
        "difficulty": "hard",
        "continent": "Amérique du Nord",
    },
    {
        "fr": "Nicaragua",
        "en": "Nicaragua",
        "capital_fr": "Managua",
        "iso2": "NI",
        "difficulty": "hard",
        "continent": "Amérique du Nord",
    },
    # Océanie
    {
        "fr": "Papouasie-Nouvelle-Guinée",
        "en": "Papua New Guinea",
        "capital_fr": "Port Moresby",
        "iso2": "PG",
        "difficulty": "hard",
        "continent": "Océanie",
    },
    {
        "fr": "Fidji",
        "en": "Fiji",
        "capital_fr": "Suva",
        "iso2": "FJ",
        "difficulty": "hard",
        "continent": "Océanie",
    },
    {
        "fr": "Îles Salomon",
        "en": "Solomon Is.",
        "capital_fr": "Honiara",
        "iso2": "SB",
        "difficulty": "hard",
        "continent": "Océanie",
    },
    {
        "fr": "Vanuatu",
        "en": "Vanuatu",
        "capital_fr": "Port-Vila",
        "iso2": "VU",
        "difficulty": "hard",
        "continent": "Océanie",
    },
]


# ── Alias anglais pour les noms de pays ──────────────────────────────────────
# Les réponses dans cette liste seront aussi acceptées
COUNTRY_ALIASES: dict[str, list[str]] = {
    "États-Unis": ["USA", "US", "United States", "America"],
    "Royaume-Uni": ["UK", "England", "Britain", "Great Britain"],
    "Corée du Sud": ["South Korea"],
    "Corée du Nord": ["North Korea"],
    "Émirats arabes unis": ["UAE", "Emirates", "United Arab Emirates"],
    "RD Congo": ["DRC", "Congo DR", "Democratic Republic of Congo", "RDC"],
    "Rép. centrafricaine": ["Central African Republic", "CAR"],
    "Bosnie-Herzégovine": ["Bosnia", "Bosnia and Herzegovina"],
    "Macédoine du Nord": ["Macedonia", "North Macedonia"],
    "Timor oriental": ["East Timor", "Timor-Leste"],
    "Papouasie-Nouvelle-Guinée": ["Papua New Guinea", "PNG"],
    "Trinité-et-Tobago": ["Trinidad and Tobago", "Trinidad"],
    "Îles Salomon": ["Solomon Islands", "Solomon Is"],
    "Russie": ["Russia"],
    "Chine": ["China"],
    "Inde": ["India"],
    "Japon": ["Japan"],
    "Brésil": ["Brazil"],
    "Mexique": ["Mexico"],
    "Allemagne": ["Germany"],
    "Espagne": ["Spain"],
    "Italie": ["Italy"],
    "Grèce": ["Greece"],
    "Suède": ["Sweden"],
    "Norvège": ["Norway"],
    "Belgique": ["Belgium"],
    "Suisse": ["Switzerland"],
    "Pologne": ["Poland"],
    "Autriche": ["Austria"],
    "Hongrie": ["Hungary"],
    "Roumanie": ["Romania"],
    "Turquie": ["Turkey"],
    "Égypte": ["Egypt"],
    "Maroc": ["Morocco"],
    "Algérie": ["Algeria"],
    "Nigéria": ["Nigeria"],
    "Éthiopie": ["Ethiopia"],
    "Afrique du Sud": ["South Africa"],
    "Arabie saoudite": ["Saudi Arabia"],
    "Indonésie": ["Indonesia"],
    "Philippines": ["Philippines"],
    "Vietnam": ["Vietnam"],
    "Thaïlande": ["Thailand"],
    "Malaisie": ["Malaysia"],
    "Singapour": ["Singapore"],
    "Bangladesh": ["Bangladesh"],
    "Pakistan": ["Pakistan"],
    "Afghanistan": ["Afghanistan"],
    "Kazakhstan": ["Kazakhstan"],
    "Mongolie": ["Mongolia"],
    "Myanmar": ["Myanmar", "Burma"],
    "Cambodge": ["Cambodia"],
    "Laos": ["Laos"],
    "Népal": ["Nepal"],
    "Bhoutan": ["Bhutan"],
    "Brunéi": ["Brunei"],
    "Kirghizistan": ["Kyrgyzstan"],
    "Tadjikistan": ["Tajikistan"],
    "Turkménistan": ["Turkmenistan"],
    "Ouzbékistan": ["Uzbekistan"],
    "Géorgie": ["Georgia"],
    "Arménie": ["Armenia"],
    "Azerbaïdjan": ["Azerbaijan"],
    "Jordanie": ["Jordan"],
    "Syrie": ["Syria"],
    "Liban": ["Lebanon"],
    "Israël": ["Israel"],
    "Irak": ["Iraq"],
    "Iran": ["Iran"],
    "Yémen": ["Yemen"],
    "Koweït": ["Kuwait"],
    "Bahreïn": ["Bahrain"],
    "Oman": ["Oman"],
    "Qatar": ["Qatar"],
    "Sri Lanka": ["Sri Lanka"],
    "Côte d'Ivoire": ["Ivory Coast"],
    "Guinée équatoriale": ["Equatorial Guinea"],
    "Guinée-Bissau": ["Guinea-Bissau"],
    "Guinée": ["Guinea"],
    "Sierra Leone": ["Sierra Leone"],
    "Libéria": ["Liberia"],
    "Mauritanie": ["Mauritania"],
    "Burkina Faso": ["Burkina Faso"],
    "Somalie": ["Somalia"],
    "Érythrée": ["Eritrea"],
    "Ouganda": ["Uganda"],
    "Namibie": ["Namibia"],
    "Botswana": ["Botswana"],
    "Lesotho": ["Lesotho"],
    "Eswatini": ["Swaziland", "eSwatini"],
    "Madagascar": ["Madagascar"],
    "Gabon": ["Gabon"],
    "Bénin": ["Benin"],
    "Togo": ["Togo"],
    "Haïti": ["Haiti"],
    "République dominicaine": ["Dominican Republic"],
    "Jamaïque": ["Jamaica"],
    "Suriname": ["Suriname"],
    "Guyana": ["Guyana"],
    "Bolivie": ["Bolivia"],
    "Équateur": ["Ecuador"],
    "Paraguay": ["Paraguay"],
    "Uruguay": ["Uruguay"],
    "Honduras": ["Honduras"],
    "Nicaragua": ["Nicaragua"],
    "Belize": ["Belize"],
    "Panama": ["Panama"],
    "Guatemala": ["Guatemala"],
    "Chypre": ["Cyprus"],
    "Malte": ["Malta"],
    "Liechtenstein": ["Liechtenstein"],
    "Andorre": ["Andorra"],
    "Islande": ["Iceland"],
    "Finlande": ["Finland"],
    "Danemark": ["Denmark"],
    "Pays-Bas": ["Netherlands"],
    "Irlande": ["Ireland"],
    "Croatie": ["Croatia"],
    "Bulgarie": ["Bulgaria"],
    "Serbie": ["Serbia"],
    "Albanie": ["Albania"],
    "Slovénie": ["Slovenia"],
    "Slovaquie": ["Slovakia"],
    "Lituanie": ["Lithuania"],
    "Lettonie": ["Latvia"],
    "Estonie": ["Estonia"],
    "Biélorussie": ["Belarus"],
    "Monténégro": ["Montenegro"],
    "Moldavie": ["Moldova"],
    "Kosovo": ["Kosovo"],
    "Fidji": ["Fiji"],
    "Vanuatu": ["Vanuatu"],
}

# ── Alias anglais pour les capitales ─────────────────────────────────────────
CAPITAL_ALIASES: dict[str, str] = {
    "Pékin": "Beijing",
    "Séoul": "Seoul",
    "Moscou": "Moscow",
    "Le Caire": "Cairo",
    "Athènes": "Athens",
    "Lisbonne": "Lisbon",
    "Vienne": "Vienna",
    "Varsovie": "Warsaw",
    "Bucarest": "Bucharest",
    "Copenhague": "Copenhagen",
    "Bruxelles": "Brussels",
    "Berne": "Bern",
    "Hanoï": "Hanoi",
    "Dacca": "Dhaka",
    "Katmandou": "Kathmandu",
    "Damas": "Damascus",
    "Téhéran": "Tehran",
    "Bagdad": "Baghdad",
    "Riyad": "Riyadh",
    "Oulan-Bator": "Ulaanbaatar",
    "Tachkent": "Tashkent",
    "Achgabat": "Ashgabat",
    "Bichkek": "Bishkek",
    "Douchanbé": "Dushanbe",
    "Tbilissi": "Tbilisi",
    "Erevan": "Yerevan",
    "Bakou": "Baku",
    "Addis-Abeba": "Addis Ababa",
    "Alger": "Algiers",
    "Yaoundé": "Yaounde",
    "Abou Dabi": "Abu Dhabi",
    "Beyrouth": "Beirut",
    "Kaboul": "Kabul",
    "Manille": "Manila",
    "Mogadiscio": "Mogadishu",
    "Londres": "London",
    "Kyiv": "Kiev",
    "Nicosie": "Nicosia",
    "Andorre-la-Vieille": "Andorra la Vella",
    "La Valette": "Valletta",
    "Phnom Penh": "Phnom Penh",
    "Lomé": "Lome",
    "Conakry": "Conakry",
    "Bangui": "Bangui",
    "Kinshasa": "Kinshasa",
    "Brazzaville": "Brazzaville",
    "Djouba": "Juba",
    "N'Djamena": "N'Djamena",
    "Ouagadougou": "Ouagadougou",
    "Porto-Novo": "Porto-Novo",
    "Antananarivo": "Antananarivo",
    "Port-au-Prince": "Port-au-Prince",
    "Saint-Domingue": "Santo Domingo",
    "Thimphou": "Thimphu",
    "Koweït City": "Kuwait City",
    "La Havane": "Havana",
    "Le Cap": "Cape Town",
    "Singapour": "Singapore",
}
